---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: argocd/argocd
        helmChart:
          name: argo-cd
          version: "7.1.0"
          repository:
            url: https://argoproj.github.io/argo-helm
