apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-svc
  name: auth-svc
  namespace: jea
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jea-auth
  type: ClusterIP
status:
  loadBalancer: {}
