apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jea-auth
  name: jea-auth
  namespace: jea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jea-auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jea-auth
    spec:
      containers:
      - image: rumpli/jea-auth
        name: jea-auth
        ports:
        - containerPort: 8080
        resources: {}
status: {}
