apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blog-rest-svc
  name: blog-rest-svc
  namespace: jea
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: jea-blog-rest
  type: ClusterIP
status:
  loadBalancer: {}
