apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jea-blog-rest
  name: jea-blog-rest
  namespace: jea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jea-blog-rest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jea-blog-rest
    spec:
      containers:
      - image: rumpli/jea-blog-rest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://blog-mysql:33060/blogrest
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: YourPassword
        name: jea-blog-rest
        ports:
        - containerPort: 8080
        resources: {}
status: {}
