---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-initdb-config
  namespace: jea
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql
  namespace: jea
spec:
  selector:
    matchLabels:
      app: auth-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-mysql
    spec:
      containers:
      - image: biarms/mysql:5.7
        name: auth-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: auth-mysql
        volumeMounts:
        - name: auth-mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: auth-mysql-persistent-storage
          mountPath: /var/lib/mysql1
      volumes:
      - name: auth-mysql-initdb
        configMap:
          name: auth-mysql-initdb-config
      - name: auth-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: auth-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql
  namespace: jea
spec:
  ports:
  - port: 33060
    targetPort: 3306
  selector:
    app: auth-mysql
