apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blog-frontend-svc
  name: blog-frontend-svc
  namespace: jea
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: jea-blog-frontend
  type: ClusterIP
status:
  loadBalancer: {}
